/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export const recommended = {
  rules: {
    'complex-condition/complex-condition': 'error',
    'complex-condition/example-rule': 'error',
  },
}
