/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { recommended } from './configs/recommended'
import complexCondition from './rules/complex-condition'
import exampleRule from './rules/example-rule'

export const configs = {
  recommended,
}

export const rules = {
  'complex-condition': complexCondition,
  'example-rule': exampleRule,
}
